In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression,Lasso, Ridge


In [2]:
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv")

In [3]:
data.head(),data.shape

(                  date  Appliances  lights  ...  Tdewpoint        rv1        rv2
 0  2016-01-11 17:00:00          60      30  ...        5.3  13.275433  13.275433
 1  2016-01-11 17:10:00          60      30  ...        5.2  18.606195  18.606195
 2  2016-01-11 17:20:00          50      30  ...        5.1  28.642668  28.642668
 3  2016-01-11 17:30:00          50      40  ...        5.0  45.410389  45.410389
 4  2016-01-11 17:40:00          60      40  ...        4.9  10.084097  10.084097
 
 [5 rows x 29 columns], (19735, 29))

In [4]:
data.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [5]:
from sklearn.metrics import r2_score

In [6]:
x1= np.array(data.T2)
y1 = np.array(data.T6)

x1 = x1.reshape(-1,1)
y1 = y1.reshape(-1,1)
x1

array([[19.2       ],
       [19.2       ],
       [19.2       ],
       ...,
       [25.62857143],
       [25.414     ],
       [25.26428571]])

In [7]:
model = LinearRegression()
model.fit(x1,y1)
y_pred = model.predict(y1)
ss = r2_score(y1,y_pred)

In [8]:
ss

-21.125293684103095

In [9]:
data = data.drop(['date','lights'], axis = 1)

In [10]:
data.head()

Appliances     T1       RH_1  ...  Tdewpoint        rv1        rv2
0          60  19.89  47.596667  ...        5.3  13.275433  13.275433
1          60  19.89  46.693333  ...        5.2  18.606195  18.606195
2          50  19.89  46.300000  ...        5.1  28.642668  28.642668
3          50  19.89  46.066667  ...        5.0  45.410389  45.410389
4          60  19.89  46.333333  ...        4.9  10.084097  10.084097

[5 rows x 27 columns]

In [27]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

In [14]:
y=data.Appliances
x = data.drop('Appliances',axis=1)

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.7, random_state = 42)

In [29]:

scaler = MinMaxScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
MAE = mean_absolute_error(y_test,y_pred)
rss = np.sum(np.square(y_test-y_pred))
MSE = rss/len(x_test)
RMSE = np.sqrt(MSE)
R2 =r2_score(y_test,y_pred)
MSE,rss,RMSE,R2

(9198.806010874383, 127081505.0402296, 95.91040616572522, 0.14347958498194002)

In [30]:
model.coef_

array([   5.12166474,  468.73282414, -258.00349818, -431.33843506,
        311.9998314 ,  105.48438744,   31.46663714,  -20.85907103,
        -25.48180859,   25.10923596,  252.78666614,   47.97639733,
         -9.55998185,  -24.6350786 ,  120.5849918 , -185.28779923,
       -194.01965309,  -30.37789368, -259.37603692,   14.56143495,
        -46.6350559 ,   37.52690767,   17.37529034,   72.39486977,
         -0.78064194,   -0.78064194])

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [34]:
model1 = Ridge(alpha=0.4)
model1.fit(x_train, y_train)
y_pred2 = model1.predict(x_test)
MAE1 = mean_absolute_error(y_test,y_pred2)
rss1 = np.sum(np.square(y_test-y_pred2))
MSE1 = rss1/len(x_test)
RMSE1 = np.sqrt(MSE1)
R21 =r2_score(y_test,y_pred2)
MSE1,rss1,RMSE1,R21

(9211.120154605265, 127251624.93587175, 95.97458077327175, 0.14233298883821233)

In [35]:
model2 = Lasso(alpha=0.4)
model2.fit(x_train, y_train)
y_pred3 = model2.predict(x_test)
MAE2 = mean_absolute_error(y_test,y_pred3)
rss2 = np.sum(np.square(y_test-y_pred3))
MSE2 = rss2/len(x_test)
RMSE2 = np.sqrt(MSE2)
R22 =r2_score(y_test,y_pred3)
MSE2,rss2,RMSE2,R22

(9724.798712232787, 134348094.20949596, 98.61439404180703, 0.09450328454345014)

In [37]:
model2.coef_

array([  -0.        ,  172.10240736,   14.88932207,   -0.        ,
         99.008203  ,    0.        ,   -0.        ,   -0.        ,
         -0.        ,    0.        ,    0.        ,    0.        ,
         -0.        ,  -21.34383127,    0.        , -125.99496138,
        -95.98457143,   -0.        ,    0.        ,   -0.        ,
        -31.18454389,   23.64885007,    5.6235125 ,   -0.        ,
         -0.        ,   -0.        ])